### ISSUE TITLE
Err is never set and catch is never called

### ISSUE THREAD

**Issue by chocolateboy** [rstacruz/read-input#1]
read-input: 0.3.1
node: v0.12.7
OS: Linux (Arch)

The documentation says:

> `err` will be given if at least one of the files fail.

And:

> If any of the files can't be read, err will be an error object.

In practice, the error is always consumed, both for stdin and for files. These examples don't set the `err` parameter in the callback or trigger the promise's `catch` handler:
### Test 1

``` javascript
var read = require('read-input');

read([ 'no-such.file' ], function (err, res) {
    if (err) {
        console.log("should get here");
    } else {
        console.log("shouldn't get here");
    }
});
```
### Output 1

> shouldn't get here
### Test 2

``` javascript
var read = require('read-input');

read([ 'no-such.file' ])
    .then(function (res) {
        console.log("shouldn't get here");
    })
    .catch(function (err) {
        console.log("should get here");
    });
```
### Output 2

> shouldn't get here
### Test 3

``` javascript
var read = require('read-input');

read([], function (err, res) {
    if (err) {
        console.log("should get here");
    } else {
        console.log("shouldn't get here");
    }
});
```
### Run 3

[Bad stdin](https://stackoverflow.com/a/22441643) (it's a directory).

```
node test3.js 0</tmp
```
### Output 3

```

Error: Implement me. Unknown stdin file type!
    at process.stdin (node.js:558:17)
    at node_modules/read-input/index.js:92:12
    at promisify (node_modules/read-input/index.js:177:5)
    at Function.read.stdin (node_modules/read-input/index.js:89:10)
    at node_modules/read-input/index.js:51:12
    at promisify (node_modules/read-input/index.js:177:5)
    at read (node_modules/read-input/index.js:48:10)
node.js:558
```

**Comment by rstacruz** [comment]
Thanks... wanna contribute a patch? :)

**Comment by chocolateboy** [comment]
> wanna contribute a patch? :)

I will if I get a chance, but feel free to beat me to it :-)
